name: "OpenChat GitHub Bot Action"
description: "A GitHub Action to post PR data to the OpenChat github bot."
inputs:
  OC_BOT_URL:
    description: "The URL of the bot endpoint."
    required: true
  OC_API_KEY:
    description: "The API key which encodes the group or channel to post the update to."
    required: true
runs:
  using: "bash"
  steps:
    - name: Post PR data
      run: |
        PR_TITLE="${{ github.event.pull_request.title }}"
        PR_URL="${{ github.event.pull_request.html_url }}"
        PR_AUTHOR="${{ github.event.pull_request.user.login }}"
        REPO_TITLE="${{ github.event.repository.name }}"

        DATA=$(jq -n \
          --arg title "$PR_TITLE" \
          --arg url "$PR_URL" \
          --arg author "$PR_AUTHOR" \
          --arg repo "$REPO_TITLE" \
          '{title: $title, url: $url, author: $author, repo: $repo}')

        echo "Posting to URL: ${{ inputs.OC_BOT_URL }}"
        echo "Data: $DATA"

        curl -X POST "${{ inputs.OC_BOT_URL }}" \
          -H "Content-Type: application/json" \
          -H "x-api-key: ${{ inputs.OC_API_KEY }}" \
          -d "$DATA"
