name: "OpenChat GitHub Bot Action"
description: "A GitHub Action to post PR data to the OpenChat GitHub bot."
inputs:
  OC_BOT_URL:
    description: "The URL of the bot endpoint."
    required: true
  OC_API_KEY:
    description: "The API key which encodes the group or channel to post the update to."
    required: true
runs:
  using: "composite"
  steps:
    - name: Extract PR Title Safely
      shell: bash
      run: echo "PR_TITLE=${{ github.event.pull_request.title }}" >> $GITHUB_ENV

    - name: Format data and send
      shell: bash
      run: |
        PR_URL="${{ github.event.pull_request.html_url }}"
        PR_AUTHOR="${{ github.event.pull_request.user.login }}"
        REPO_TITLE="${{ github.event.repository.name }}"

        DATA=$(jq -n \
          --arg title "$PR_TITLE" \
          --arg url "$PR_URL" \
          --arg author "$PR_AUTHOR" \
          --arg repo "$REPO_TITLE" \
          '{title: $title, url: $url, author: $author, repo: $repo}')

        echo "Posting to URL: ${{ inputs.OC_WEBHOOK_URL }}"
        echo "Data: $DATA"

        curl -X POST "${{ inputs.OC_WEBHOOK_URL }}" \
          -H "Content-Type: application/json" \
          -d "$DATA"
